### PR TITLE
validation_utils IsEmpty doesn't check for boolean values

### PR DESCRIPTION
**Pull request by hedenface**
Signed-off-by: Bryan Heden <b.heden@gmail.com>

In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware/terraform-provider-vcf/blob/main/CONTRIBUTING.md) for making a pull request.

**Summary of Pull Request**
This offers a fix during vcf_domain creation when defining an nfs_datastore. The validation_utils.IsEmpty function doesn't check properly for a boolean value. This could also fix potential bugs in a few other places.
https://github.com/vmware/terraform-provider-vcf/blob/v0.2.0/internal/datastores/nfs_datastore_subresource.go#L68-L72

**Type of Pull Request**

- [x] This is a bug fix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style/formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is a chore update
- [ ] This is something else.
      Please describe:

**Related to Existing Issues**

Issue Number: N/A

**Test and Documentation Coverage**

For bug fixes or features:

- [ ] Tests have been completed.
- [ ] Documentation has been added/updated.

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Comment by hedenface** [comment]
@tenthirtyam This is the follow up to 45, appropriately signed.

**Comment by hedenface** [comment]
So, going through the codebase, it looks like this fix affects the bug I already listed in the description, but also probably the following locations:
* https://github.com/vmware/terraform-provider-vcf/blob/main/internal/datastores/vsan_datastore_subresource.go#L59-L61
* https://github.com/vmware/terraform-provider-vcf/blob/main/internal/network/vds_subresource.go#L63-L65

**Comment by dimitarproynov** [comment]
Thanks!

**Review by dimitarproynov — APPROVED** [review]

**Comment by dimitarproynov** [comment]
I'm struggling with some unexpected behavior in Acceptance E2E tests, but I'm planning a release right after the struggle is over.

**Pull request merged**
